version: '3.7'
services:
  php:
    build: .
    container_name: amoretti-php
    depends_on:
      - mysql
    environment:
      SYMFONY_PHPUNIT_VERSION: '9'
      COMPOSER_ALLOW_SUPERUSER: 1
      DB_PASSWORD: 1234
      DB_USER: exadsdb
      DB_NAME: exads
      DB_HOST: mysql
      DB_PORT: 3306
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:rw

  mysql:
    image: mysql:5.7
    container_name: amoretti-db
    environment:
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=exadsdb
      - MYSQL_DATABASE=exads
      - MYSQL_HOST_IP=0.0.0.0
    ports:
      - 3206:3306
    volumes:
      - ./src/Database/Resources/database.sql:/docker-entrypoint-initdb.d/exads_test.sql

  nginx:
    image: nginx:1.17
    container_name: amoretti-server
    depends_on:
      - php
    ports:
      - 8090:80
    volumes:
      - .:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro